import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Portal News",
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <div className="antialiased text-gray-800">
            <Navbar/>
            <main className="container px-8 mx-auto xl:px-5 max-w-screen-lg py-5 lg:-py-5">
                {children}
            </main>
            <Footer/>
        </div>
    )
}
